version: '3.7'

services:
  web:
    container_name: web_events
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/events
    ports:
      - 8000:8000
      - 80:8000
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres_events
    image: postgres:13.8
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U events_user -d events_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_events
    depends_on:
      postgres:
        condition: service_healthy
    image: dpage/pgadmin4:6.14
    environment:
      PGADMIN_DEFAULT_EMAIL: "events@example.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped